### ISSUE TITLE
Automatic link to notebook and native python support

### ISSUE THREAD

**Issue by albertomercurio** [coatless-quarto/colab#6]
Hello,

I was wondering if it were possible to have the "Open in Colab" button that opens the related notebook automatically. For the moment I have to manually set the link of the notebook.

Moreover, it seems from the documentation that python is only supported through R, using

```yaml
setup-cells:
  r:
    language: "python"    # Language assumed for the setup cell
    code: |
      # Custom R setup
      !pip install rpy2
      %load_ext rpy2.ipython
```

Is there a way to have it natively?
